### ISSUE TITLE
Card Patched Still Unable to past Bios Whitelist

### ISSUE THREAD

**Issue by ikonman** [nouatzi/AR9285-rebranding#1]
Hi,

I've followed your tutorial and managed to rebrand my Atheros 9825 into Intel wireless card. But after I plug it in on the x230, it still won't pass the whitelist. I'm using latest bios for x230, v2.70. Any suggestion.

Thanks,

Ardy

**Comment by nouatzi** [comment]
Hi, What does it say exactly ?
It would be good to have the messages from the X230 with:
- the unmodified Atheros card
- the modified Atheros card

So we can compare them and see what wrong.
By the way, I'm using BIOS v2.67
Which OS do you intend to use with the X230 ?

**Comment by ikonman** [comment]
It says like usual when non whitelisted card inserted to the machine. Is it possible that this rebranding is blocked on bios 2.70?

**Comment by nouatzi** [comment]
Can you tell me the exact message ? It will help to identify what's wrong.
Yes, it might be the bios version.
Which OS do you intend to use with the X230 ?

**Comment by ikonman** [comment]
- Message: 1002: unauthorized network card is plugged in  - Power off and remove the miniPCI network card (0CF3/3002). System is halted
- In OSX 10.12.6, the OSX is there already, just missing internal wifi card. Currently I'm using usb wifi dongle.

Btw, thanks a lot for helping me

**Comment by nouatzi** [comment]
Well, I don't think your bios version is causing this.
According to the message : 0CF3/3002 are the values you entered, which are wrong IDs.
The first time I've tried, I entered the wrong ID values, and I got a message like this.
Now, what you have to do, is to put the untouched eeprom (the backup) back into your card and start again. 
BUT, right now, the card ID is not recognizable by Ubuntu, because the ID is wrong, so it won't recognize your card, so you won't be able to put back the original eeprom.

[How to repair an Atheros 92xx based WiFi card, flashed with wrong IDs
](https://www.tonymacx86.com/threads/rebranding-the-atheros-928x-cards-the-guide.115110/page-7#post-816640)

I used that method to restore my card after the first failed attempt.

Just to know, when you've followed my tutorial, did you encounter any issue or weird stuff, or anything different ?

**Comment by ikonman** [comment]
My Intel N6205 Card ID (PCI ID & Subsys) are exactly like what you described on the tutorial, but my AR9285 card has:
- PCI_ID: 168C:002B (Same as yours)
- PCI_SUBSYS_ID: 17AA:31A1 -> This one I should search for AA17A131 on the hex to be replaced right?

I didn't encounter any issue, your tutorial is pretty clear for me.

**Comment by nouatzi** [comment]
Indeed yes, it should have worked... Just to be sure, you didn't type any space bar character or : character ?
Anyway, now it's time to [put back the original backup eeprom](https://www.tonymacx86.com/threads/rebranding-the-atheros-928x-cards-the-guide.115110/page-7#post-816640) by using your wrong PCI IDs (0CF3:3002).

**Comment by ikonman** [comment]
Hi, I've check the patched rom. And I'm pretty sure I already did exactly like the tutorial, below are my change (byte flip)
PCI_ID: 8C162B00 -> REPLACE WITH 86808500
PCI_SUBSYS_ID: AA17A131 -> REPLACE WITH 86801113 

Here are my Original & Patched Rom: [Rom Link](https://we.tl/v4er38QvmV)

If you have time, please take a look at it. Its really confuse me.

**Comment by ikonman** [comment]
No luck in restoring AR9285 to original rom, error during compiling code:

cc -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer   -c -o conf.o conf.c
cc   conf.o zconf.tab.o   -o conf
boolean symbol HWMON tested for 'm'? test forced to 'n'
boolean symbol HWMON tested for 'm'? test forced to 'n'
#
# configuration written to .config
#
Building backport-include/backport/autoconf.h ... done.
  CC [M]  /home/ubuntu/Downloads/backports-4.1.1-1/compat/main.o
In file included from /home/ubuntu/Downloads/backports-4.1.1-1/backport-include/backport/backport.h:7:0,
                 from <command-line>:0:
./include/asm-generic/qrwlock.h: In function ‘__qrwlock_write_byte’:
/home/ubuntu/Downloads/backports-4.1.1-1/backport-include/linux/kconfig.h:25:28: error: implicit declaration of function ‘config_enabled’ [-Werror=implicit-function-declaration]
 #define IS_BUILTIN(option) config_enabled(option)
                            ^
./include/asm-generic/qrwlock.h:156:26: note: in expansion of macro ‘IS_BUILTIN’
  return (u8 *)lock + 3 * IS_BUILTIN(CONFIG_CPU_BIG_ENDIAN);
                          ^~~~~~~~~~
./include/asm-generic/qrwlock.h:156:37: error: ‘CONFIG_CPU_BIG_ENDIAN’ undeclared (first use in this function); did you mean ‘CONFIG_CPU_SUP_INTEL’?
  return (u8 *)lock + 3 * IS_BUILTIN(CONFIG_CPU_BIG_ENDIAN);
                                     ^
/home/ubuntu/Downloads/backports-4.1.1-1/backport-include/linux/kconfig.h:25:43: note: in definition of macro ‘IS_BUILTIN’
 #define IS_BUILTIN(option) config_enabled(option)
                                           ^~~~~~
./include/asm-generic/qrwlock.h:156:37: note: each undeclared identifier is reported only once for each function it appears in
  return (u8 *)lock + 3 * IS_BUILTIN(CONFIG_CPU_BIG_ENDIAN);
                                     ^
/home/ubuntu/Downloads/backports-4.1.1-1/backport-include/linux/kconfig.h:25:43: note: in definition of macro ‘IS_BUILTIN’
 #define IS_BUILTIN(option) config_enabled(option)
                                           ^~~~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:302: recipe for target '/home/ubuntu/Downloads/backports-4.1.1-1/compat/main.o' failed
make[6]: *** [/home/ubuntu/Downloads/backports-4.1.1-1/compat/main.o] Error 1
scripts/Makefile.build:575: recipe for target '/home/ubuntu/Downloads/backports-4.1.1-1/compat' failed
make[5]: *** [/home/ubuntu/Downloads/backports-4.1.1-1/compat] Error 2
Makefile:1546: recipe for target '_module_/home/ubuntu/Downloads/backports-4.1.1-1' failed
make[4]: *** [_module_/home/ubuntu/Downloads/backports-4.1.1-1] Error 2
Makefile.build:6: recipe for target 'modules' failed
make[3]: *** [modules] Error 2
Makefile.real:88: recipe for target 'modules' failed
make[2]: *** [modules] Error 2
Makefile:40: recipe for target 'modules' failed
make[1]: *** [modules] Error 2
Makefile:30: recipe for target 'default' failed
make: *** [default] Error 2

**Comment by nouatzi** [comment]
I took a look at you eeproms, and they seem OK.
Did you, by any chance, kept the log of iwleeprom ? like this one:

> Supported devices detected:
>   [1] 0000:03:00.0 [RW] AR9285 Wireless Adapter (PCI-E) (168c:002b, 1a3b:1089)
> Select device [1-1] (or 0 to quit): 1
> Using device 0000:03:00.0 [RW] AR9285 Wireless Adapter (PCI-E)
> IO driver: ath9k
> HW: AR9285 (PCI-E) rev 0002
> RF: integrated
> Checking NVM size...
> ath9k short eeprom base: 0  size: 512
> Saving dump with byte order: LITTLE ENDIAN

[I've found this](https://www.tonymacx86.com/threads/guide-lenovo-ideapad-u330-u430-u530-using-clover-uefi.155106/page-3#post-978147)

**Comment by ikonman** [comment]
Nope, I didn't have it. So the card is officially go to trash. Thanks so much for all your help and advice. Too bad I can't recover it.

**Comment by nouatzi** [comment]
backports are used to compile a wireless driver with the wrong IDs. 
if backports don't work, there are other ways to compile the ath wireless linux driver.

If you don't want to bother with flashing eeprom, there is [a card](https://github.com/Bizzaro/x230-osx/issues/2#issuecomment-312294214) that seems to be whitelisted by Lenovo and supported in macOS.

**Comment by ikonman** [comment]
What is the other way to compile the ath wireless linux driver, do you have any link that I can try.

**Comment by nouatzi** [comment]
If you're on Ubuntu, you can try [this](https://help.ubuntu.com/community/Kernel/Compile#AltBuildMethod), it will compile the entire kernel and it drivers, which might take some times.
Otherwise, you can try [this](https://askubuntu.com/questions/515407/how-recipe-to-build-only-one-kernel-module) or [this](https://www.cnx-software.com/2015/03/06/how-to-build-a-single-kernel-module-driver-in-ubuntu/) in order to compile only one kernel.

**Comment by nouatzi** [comment]
And when you download the kernel, choosee one with your actual version (for example mine is 4.4.0)

**Comment by nouatzi** [comment]
@ikonman I have updated the tutorial, in order to restore the eeprom, so you can take a look. ;) Don't hesitate to tell me what you think.

**Comment by ikonman** [comment]
Hi @nouatzi thanks for this. My card is actually AR5B195 which based on google search has 2 module, wifi and Bluetooth, the wifi is AR9285, and it seems the one rejected by x230 bios is the bluetooth module, since I didn't rebrand that.

Friend of mine able to bypass x230 whitelist using wifi card from Lenovo G470, it was AR9285, I think its FRU related so this card can bypass the bios. I'll try your guide when I have a chance, thanks so much.
